# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='course_code',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
