# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0006_auto_20160819_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='remail_public',
            new_name='email_public',
        ),
    ]
