# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0007_auto_20160819_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ideal_study_group',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='major',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='minor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(default='image_not_available.jpg', upload_to='images'),
        ),
    ]
