# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0009_auto_20160819_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='location_desc',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='name',
            field=models.CharField(default='no name', max_length=20),
            preserve_default=False,
        ),
    ]
