# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 01:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0011_auto_20160820_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='course_code',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Improper Course Code Format! (EX: INFO 344, PHYS 444H)', regex='^[a-zA-Z]* [0-9]{2,3}[a-zA-Z]{0,2}$')]),
        ),
    ]
